### ISSUE TITLE
external battery

### ISSUE THREAD

**Issue by ranshalit** [thuetz/Energize#39]
Hello,

I would please like to ask about battery remaining time application.
Can it also measure the remaining time for external battery (connected through usb) ?

Thank you!
Ran

**Comment by thuetz** [comment]
Hi Ran,

sorry for the late reply. Unfortunately, this feature cannot be implemented since Android has no build-in functions for gathering information about the external battery. I think this is not an issue in the OS itself, it's more a problem of the battery not reporting it's state to the connected devices.

Best,
Tim

**Comment by ranshalit** [comment]
Hi Tim,

That's the most accurate answer I got on this subject.

Thank you very much!
Ran

**Comment by thuetz** [comment]
You are welcome. Sorry that I could not help you!

Best,
Tim
